### ISSUE TITLE
Does not handle conflicting versions of build dependencies

### ISSUE THREAD

**Issue by chmeliik** [bruno-fs/pybuild-deps#186]
When installing from source, the build dependencies of each package are typically installed in an isolated environment. A conflict between the build dependencies of two different packages should not be considered a conflict. See https://peps.python.org/pep-0517/#recommendations-for-build-frontends-non-normative (pip does implement build isolation).

Currently, `pybuild-deps` does fail on such conflicts.

### Reproducer

```requirements.txt
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile requirements.in
#
click==8.1.7
    # via typer
packaging==24.1
    # via -r requirements.in
typer==0.10.0
    # via -r requirements.in
typing-extensions==4.12.2
    # via typer
```

```bash
$ pybuild-deps compile requirements.txt
No output file (-o) specified. Defaulting to 'dry run' mode.
  ERROR: Cannot install flit_core<3 and >=2 and flit_core>=3.3 because these package versions have conflicting dependencies.
Impossible resolve dependencies. See the conflicting dependencies below:
flit_core>=3.3 (from packaging)
flit_core<3,>=2 (from typer)
flit_core<4,>=3.4 (from typing-extensions)
```

`typer==0.10` requires `flit_core<3`
`typing-extensions==4.12.2` requires `flit_core>=3.4`

### Expected behavior

`pybuild-deps` creates multiple output files to separate the conflicting build dependencies (optionally, can provide a flag to leave conflicting deps in the same file, making it unusable with `pip download` but usable with e.g. [cachi2](https://github.com/containerbuildsystem/cachi2))

**Comment by chmeliik** [comment]
Btw, thanks a lot for creating this tool :tada: 

We're looking into making this the official recommendation in https://github.com/containerbuildsystem/cachi2/blob/main/docs/pip.md#requirements-buildtxt, so we're evaluating it a bit more closely (context for this issue and perhaps a few more :slightly_smiling_face: )

**Comment by brunoapimentel** [comment]
I believe this issue was fixed in the latest release. When I process the requirements file you posted, I get this as output:
```
#
# This file is autogenerated by pip-compile with Python 3.9
# by the following command:
#
#    pybuild-deps compile /tmp/pytest/requirements.txt
#
flit-core==3.9.0
    # via
    #   packaging
    #   typing-extensions
flit-core==2.3.0
    # via typer
pytoml==0.1.21
    # via flit-core
```

There's no option to split the conflicting versions into separate files, though.

**Comment by bruno-fs** [comment]
Gonna close it for now. The behavior 0.0.3 version fixes the issue and I particularly don't see a need for the old behavior. The old behavior was only there because it was much easier to implement.
